### PR TITLE
Solutions for subsection 5.4.3 Pairing groups 

### PR DESCRIPTION
**Pull request by skaunov**
Sorry, @erhant , updating <branch:patch-4> didn't worked for me, as I had to store some drafts which shouldn't be updating the PR from that branch.

### CODE REVIEW

**Comment by skaunov** [comment]
I need to put some more effort into exercise 83...

**Comment by skaunov** [comment]
should be done now \
though further correction is possible :sweat_smile:

**Comment by skaunov** [comment]
https://github.com/erhant/moonmath/pull/13#discussion_r1336510411
I was just pretty lost around... Actually what is needed here is just do that trick again with scalar multiplication of the number in question and checking equality to $(0:1:0)$.

Also, pls, note it requires some more work here to become correct solutions.

**Comment by skaunov** [comment]
I'll remove exercise 83 from this one. Would wrap up if anyone is interested.

Also I'll check the other one exercise; pretty sure it's incorrect now.

**Comment by skaunov** [comment]
Suddenly, I corrected both of the exercises! (And also had a tricky question along the way.)
Let me send you review request for that matter.

**Comment by erhant** [comment]
Merging to a common branch, as done with #13

**Pull request merged**
